// Mocks generated by Mockito 5.4.6 from annotations
// in ceiba_project/test/features/funds/data/datasources/funds_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ceiba_project/core/services/persistence_service.dart' as _i2;
import 'package:ceiba_project/features/funds/domain/entities/fund.dart' as _i4;
import 'package:ceiba_project/features/funds/domain/entities/fund_transaction.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistenceService extends _i1.Mock
    implements _i2.PersistenceService {
  MockPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveFunds(List<_i4.Fund>? funds) =>
      (super.noSuchMethod(
            Invocation.method(#saveFunds, [funds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Fund>> loadFunds() =>
      (super.noSuchMethod(
            Invocation.method(#loadFunds, []),
            returnValue: _i3.Future<List<_i4.Fund>>.value(<_i4.Fund>[]),
          )
          as _i3.Future<List<_i4.Fund>>);

  @override
  _i3.Future<void> saveTransactions(List<_i5.FundTransaction>? transactions) =>
      (super.noSuchMethod(
            Invocation.method(#saveTransactions, [transactions]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.FundTransaction>> loadTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#loadTransactions, []),
            returnValue: _i3.Future<List<_i5.FundTransaction>>.value(
              <_i5.FundTransaction>[],
            ),
          )
          as _i3.Future<List<_i5.FundTransaction>>);

  @override
  _i3.Future<void> saveBalance(double? balance) =>
      (super.noSuchMethod(
            Invocation.method(#saveBalance, [balance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<double> loadBalance() =>
      (super.noSuchMethod(
            Invocation.method(#loadBalance, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> saveAll(
    List<_i4.Fund>? funds,
    List<_i5.FundTransaction>? transactions,
    double? balance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [funds, transactions, balance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> loadAll() =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
